### ISSUE TITLE
Use style classes instead of two styles

### ISSUE THREAD

**Issue by friedbunny** [friedbunny/ambient-light#1]
Using style classes in a single style will allow an animated transition, unlike the entire reload we're doing now between two styles.

**Comment by 1ec5** [comment]
At one point, we discussed shipping Light and Dark as one style using style classes, but we settled on two styles. @peterqliu may remember why.

**Comment by peterqliu** [comment]
for Light/Dark, I think there might be subtle differences in styling besides coloration. @andreasviglakis would be in a better position to answer

**Comment by friedbunny** [comment]
Chatted with @andreasviglakis today, I'll look into doing this myself.

**Comment by friedbunny** [comment]
Nope — punting on this until style classes become better supported.
